---
title: "Multilevel Model with Compositional Outcomes"
output: 
  html_document:
    theme: sandstone
    highlight: zenburn
    toc: yes
    toc_float: yes
    collapsed: no
    smooth_scroll: no
    toc_depth: 4
    fig_width: 6
    fig_height: 4
    fig_caption: yes
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Multilevel Model with Compositional Outcomes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



In this vignette, we discuss how to specify multilevel models with compositional outcomes using `multilevelcoda`. 
In addition to `multilevelcoda`, we will use `brms` package (to fit models) and
`bayestestR` package (to compute useful indices and compare models). 
We will also attach built in datasets `mcompd` (simulated compositional sleep and wake variables) 
and `sbp` (sequential binary partition).


```r
library(multilevelcoda)
library(brms)
library(bayestestR)

data("mcompd") 
data("sbp") 

options(digits = 3)
```

# Multilevel model with compositional outcomes.
## Computing compositions and isometric log ratio coordinates. 
The ILR coordinates outcomes can be calculated using the `compilr()` functions.


```r
cilr <- compilr(data = mcompd, sbp = sbp,
                parts = c("TST", "WAKE", "MVPA", "LPA", "SB"), idvar = "ID")

head(cilr$TotalILR)
#>        ilr1 ilr2    ilr3  ilr4
#> [1,]  0.287 1.20  0.6270 1.702
#> [2,] -0.472 1.57 -0.8336 0.984
#> [3,] -0.486 1.33  1.3344 2.659
#> [4,] -0.316 1.37 -0.0332 0.551
#> [5,]  0.205 1.43 -0.6893 0.733
#> [6,] -0.446 1.16 -0.0950 0.670
```

## Fitting model

A model with multilevel compositional outcomes is multivariate, as it has multiple ILR coordinate outcomes,each of which is predicted by a set of predictors. 
Our `brms` model can be then fitted using the `brmcoda()` function.


```r
mv <- brmcoda(compilr = cilr,
              formula = mvbind(ilr1, ilr2, ilr3, ilr4) ~ STRESS + (1 | ID),
              cores = 8, seed = 123, backend = "cmdstanr")
#> Setting 'rescor' to TRUE by default for this model
#> Warning: In the future, 'rescor' will be set to FALSE by default for all models. It is thus recommended to
#> explicitely set 'rescor' via 'set_rescor' instead of using the default.
#> Compiling Stan program...
#> In file included from /var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb249b291a4.hpp:1:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/src/stan/model/model_header.hpp:4:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math.hpp:19:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/rev.hpp:10:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/rev/fun.hpp:196:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor.hpp:14:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor/integrate_ode_rk45.hpp:6:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor/ode_rk45.hpp:9:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/numeric/odeint.hpp:76:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/numeric/odeint/integrate/observer_collection.hpp:23:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function.hpp:30:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function/detail/prologue.hpp:17:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function/function_base.hpp:21:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/type_index.hpp:29:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/type_index/stl_type_index.hpp:47:
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:132:33: warning: 'unary_function<const std::error_category *, unsigned long>' is deprecat
#> ed [-Wdeprecated-declarations]
#>         struct hash_base : std::unary_function<T, std::size_t> {};
#>                                 ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:692:18: note: in instantiation of template class 'boost::hash_detail::hash_base<const std::error_category *>' requested here
#>         : public boost::hash_detail::hash_base<T*>
#>                  ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:420:24: note: in instantiation of template class 'boost::hash<const std::error_category *>' requested here
#>         boost::hash<T> hasher;
#>                        ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:551:9: note: in instantiation of function template specialization 'boost::hash_combine<const std::error_category *>' requested here
#>         hash_combine(seed, &v.category());
#>         ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/unary_function.h:23:29: note: 'unary_function<const std::error_category *, unsigned long>' has been explicitly marked deprecated here
#> struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX11 unary_function
#>                             ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:825:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#> #    define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
#>                                         ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:810:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#> #      define _LIBCPP_DEPRECATED __attribute__((deprecated))
#>                                                 ^
#> 1 warning generated.
#> Start sampling
```

Here is a `summary()` of the model. 
We can see that stress significantly predicted `ilr1` and `ilr2`. 


```r
summary(mv$Model)
#>  Family: MV(gaussian, gaussian, gaussian, gaussian) 
#>   Links: mu = identity; sigma = identity
#>          mu = identity; sigma = identity
#>          mu = identity; sigma = identity
#>          mu = identity; sigma = identity 
#> Formula: ilr1 ~ STRESS + (1 | ID) 
#>          ilr2 ~ STRESS + (1 | ID) 
#>          ilr3 ~ STRESS + (1 | ID) 
#>          ilr4 ~ STRESS + (1 | ID) 
#>    Data: tmp (Number of observations: 3540) 
#>   Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
#>          total post-warmup draws = 4000
#> 
#> Group-Level Effects: 
#> ~ID (Number of levels: 266) 
#>                    Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> sd(ilr1_Intercept)     0.33      0.02     0.30     0.37 1.00     1193     2447
#> sd(ilr2_Intercept)     0.30      0.02     0.28     0.34 1.00     1224     1704
#> sd(ilr3_Intercept)     0.39      0.02     0.35     0.43 1.00     1669     2644
#> sd(ilr4_Intercept)     0.30      0.02     0.27     0.33 1.00     1656     2347
#> 
#> Population-Level Effects: 
#>                Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> ilr1_Intercept    -0.43      0.02    -0.48    -0.39 1.00     1292     2228
#> ilr2_Intercept     1.47      0.02     1.42     1.51 1.00     1064     1883
#> ilr3_Intercept    -0.87      0.03    -0.94    -0.81 1.00     1655     2267
#> ilr4_Intercept     0.65      0.02     0.60     0.69 1.00     1966     2832
#> ilr1_STRESS       -0.01      0.00    -0.02    -0.00 1.00     6407     2823
#> ilr2_STRESS        0.01      0.00     0.00     0.01 1.00     5811     3727
#> ilr3_STRESS        0.00      0.01    -0.01     0.01 1.00     7236     3580
#> ilr4_STRESS        0.01      0.00    -0.00     0.01 1.00     7138     3403
#> 
#> Family Specific Parameters: 
#>            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> sigma_ilr1     0.44      0.01     0.43     0.45 1.00     5959     3318
#> sigma_ilr2     0.38      0.00     0.37     0.39 1.00     6830     3418
#> sigma_ilr3     0.70      0.01     0.68     0.71 1.00     6090     3393
#> sigma_ilr4     0.53      0.01     0.51     0.54 1.00     5943     3525
#> 
#> Residual Correlations: 
#>                   Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
#> rescor(ilr1,ilr2)    -0.54      0.01    -0.57    -0.52 1.00     5617     3020
#> rescor(ilr1,ilr3)    -0.18      0.02    -0.21    -0.14 1.00     6172     3721
#> rescor(ilr2,ilr3)    -0.05      0.02    -0.09    -0.02 1.00     5786     3297
#> rescor(ilr1,ilr4)     0.11      0.02     0.08     0.14 1.00     6200     3589
#> rescor(ilr2,ilr4)    -0.05      0.02    -0.08    -0.02 1.00     5772     3257
#> rescor(ilr3,ilr4)     0.56      0.01     0.53     0.58 1.00     6407     3456
#> 
#> Draws were sampled using sample(hmc). For each parameter, Bulk_ESS
#> and Tail_ESS are effective sample size measures, and Rhat is the potential
#> scale reduction factor on split chains (at convergence, Rhat = 1).
```

# Bayes Factor for compositional multilevel modelling

We are often interested in whether a predictor significantly predict the overall composition, in addition to the individual ILR coordinates. 
In Bayesian, this can be done by comparing the marginal likelihoods of two models. 
Bayes Factors (BFs) are indices of relative evidence of one model over another. 
In the context of compositional multilevel modelling, Bayes Factors provide two main useful functions:

- Testing single parameters within a model
- Comparing models 

We can utilize Bayes factors to answer the following question: 
*"Which model (i.e., set of composition predictors, expressed as ILRs) is more likely to have produced the observed data?"*

Let's examine whether stress predicts the overall sleep-wake composition.

*Note*: To use Bayes factors, `brmsfit` models must be fitted with an additional non-default argument
`save_pars = save_pars(all = TRUE)`.


```r
# intercept only
mv0 <- brmcoda(compilr = cilr,
               formula = mvbind(ilr1, ilr2, ilr3, ilr4) ~ 1 + (1 | ID),
               iter = 6000, chains = 8, cores = 8, seed = 123, warmup = 1000,
               backend = "cmdstanr", save_pars = save_pars(all = TRUE))
#> Setting 'rescor' to TRUE by default for this model
#> Warning: In the future, 'rescor' will be set to FALSE by default for all models. It is thus recommended to
#> explicitely set 'rescor' via 'set_rescor' instead of using the default.
#> Compiling Stan program...
#> In file included from /var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.hpp:1:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/src/stan/model/model_header.hpp:4:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math.hpp:19:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/rev.hpp:10:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/rev/fun.hpp:196:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor.hpp:14:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor/integrate_ode_rk45.hpp:6:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor/ode_rk45.hpp:9:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/numeric/odeint.hpp:76:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/numeric/odeint/integrate/observer_collection.hpp:23:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function.hpp:30:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function/detail/prologue.hpp:17:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function/function_base.hpp:21:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/type_index.hpp:29:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/type_index/stl_type_index.hpp:47:
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:132:33: warning: 'unary_function<const std::error_category *, unsigned long>' is deprecat
#> ed [-Wdeprecated-declarations]
#>         struct hash_base : std::unary_function<T, std::size_t> {};
#>                                 ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:692:18: note: in instantiation of template class 'boost::hash_detail::hash_base<const std::error_category *>' requested here
#>         : public boost::hash_detail::hash_base<T*>
#>                  ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:420:24: note: in instantiation of template class 'boost::hash<const std::error_category *>' requested here
#>         boost::hash<T> hasher;
#>                        ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:551:9: note: in instantiation of function template specialization 'boost::hash_combine<const std::error_category *>' requested here
#>         hash_combine(seed, &v.category());
#>         ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/unary_function.h:23:29: note: 'unary_function<const std::error_category *, unsigned long>' has been explicitly marked deprecated here
#> struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX11 unary_function
#>                             ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:825:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#> #    define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
#>                                         ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:810:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#> #      define _LIBCPP_DEPRECATED __attribute__((deprecated))
#>                                                 ^
#> 1 warning generated.
#> Start sampling
#> Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 3 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 3
#> Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 3 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 3
#> Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 3 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 3
#> Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 3 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 3
#> Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 3 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 3
#> Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 3 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 3
#> Chain 3 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 3 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 3 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 3 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 3
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[3] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb25edb8cee.stan', line 141, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
# full model
mv <- brmcoda(compilr = cilr,
              formula = mvbind(ilr1, ilr2, ilr3, ilr4) ~ STRESS + (1 | ID),
              iter = 6000, chains = 8, cores = 8, seed = 123, warmup = 1000,
              backend = "cmdstanr", save_pars = save_pars(all = TRUE))
#> Setting 'rescor' to TRUE by default for this model
#> Warning: In the future, 'rescor' will be set to FALSE by default for all models. It is thus recommended to
#> explicitely set 'rescor' via 'set_rescor' instead of using the default.
#> Compiling Stan program...
#> In file included from /var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.hpp:1:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/src/stan/model/model_header.hpp:4:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math.hpp:19:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/rev.hpp:10:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/rev/fun.hpp:196:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor.hpp:14:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor/integrate_ode_rk45.hpp:6:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/stan/math/prim/functor/ode_rk45.hpp:9:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/numeric/odeint.hpp:76:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/numeric/odeint/integrate/observer_collection.hpp:23:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function.hpp:30:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function/detail/prologue.hpp:17:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/function/function_base.hpp:21:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/type_index.hpp:29:
#> In file included from /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/type_index/stl_type_index.hpp:47:
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:132:33: warning: 'unary_function<const std::error_category *, unsigned long>' is deprecate
#> d [-Wdeprecated-declarations]
#>         struct hash_base : std::unary_function<T, std::size_t> {};
#>                                 ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:692:18: note: in instantiation of template class 'boost::hash_detail::hash_base<const std::error_category *>' requested here
#>         : public boost::hash_detail::hash_base<T*>
#>                  ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:420:24: note: in instantiation of template class 'boost::hash<const std::error_category *>' requested here
#>         boost::hash<T> hasher;
#>                        ^
#> /Users/florale/.cmdstan/cmdstan-2.30.1/stan/lib/stan_math/lib/boost_1.78.0/boost/container_hash/hash.hpp:551:9: note: in instantiation of function template specialization 'boost::hash_combine<const std::error_category *>' requested here
#>         hash_combine(seed, &v.category());
#>         ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/unary_function.h:23:29: note: 'unary_function<const std::error_category *, unsigned long>' has been explicitly marked deprecated here
#> struct _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX11 unary_function
#>                             ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:825:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX11'
#> #    define _LIBCPP_DEPRECATED_IN_CXX11 _LIBCPP_DEPRECATED
#>                                         ^
#> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:810:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#> #      define _LIBCPP_DEPRECATED __attribute__((deprecated))
#>                                                 ^
#> 1 warning generated.
#> Start sampling
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
#> Chain 7 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
#> Chain 7 Exception: multi_normal_cholesky_lpdf: Location parameter[1] is -inf, but must be finite! (in '/var/folders/fd/yjc3115x11v279rv07jxd0f40000gn/T/RtmpLRXyiz/model-bdb2b9bedb5.stan', line 181, column 4 to column 57)
#> Chain 7 If this warning occurs sporadically, such as for highly constrained variable types like covariance matrices, then the sampler is fine,
#> Chain 7 but if this warning occurs often then your model may be either severely ill-conditioned or misspecified.
#> Chain 7
```

We can now compare these models with the `bayesfactor_models()` function


```r
comparison <- bayesfactor_models(mv$Model, denominator = mv0$Model)
```



```r
comparison
#> Bayes Factors for Model Comparison
#> 
#>     Model       BF
#> [1]       2.22e-05
#> 
#> * Against Denominator: [2]
#> *   Bayes Factor Type: marginal likelihoods (bridgesampling)
```

With a $BF$ < 1, our data favours the intercept only model, showing that there is 
insufficient evidence for stress predicting the overall sleep-wake composition.

Bayes factors provide a intuitive measure of the strength of evidence of one model over the other
or among different models. Check out the `bayestestR` packages for several other useful functions related to BFs.
