---
title: "Introduction to Compositional Multilevel Modelling"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Introduction to Compositional Multilevel Modelling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The `multilevelcoda` package implements Bayesian multilevel models for compositional data in R,
by combining the principles of the two well-known analyses, Multilevel Modelling and Compositional Data Analysis.
Formula syntax is built using package brms and is similar to package lme4, which allows for 
different modelling options in a multilevel framework. The package also provides several useful functions for post-hoc analyses and visualisation of final results.

## Compositional Data Analysis

Compositional data analysis (CoDA) is an analysis of compositional and multivariate positive data.
Compositional data are typically expressed in amount, e.g., percentage, proportion, 
and often sum up to a constant, usually 100% or one. These data are common in many fields:
ecology (e.g., relative abundances of species), geography (e.g., proportions of land use), 
biochemistry (e.g., fatty acid proportions), nutritional epidemiology (e.g., intake of macronutrients 
like proteins, fats and carbohydrates), and time-use epidemiology (e.g., time spent in different
sleep-wake behaviours during the 24-hour day).

## Multilevel Modelling for Compositional Data

Compositional data can be non-independent and repeated measures data. For example, sleep-wake 
behaviours are often measured across multiple time points (e.g., across several consecutive days). 

Therefore, we often use multilevel models to include both fixed effects (regression coefficients that are identical for everyone) and random effects (regression coefficients that vary randomly for each person). In addition, we can also decompose these data into two sources of variability:
between-person (differences between individuals) and within-person (differences within individuals).

In `multilevelcoda` package, we implements Compositional Multilevel Model to model compositional data 
in amultilevel framework. `mulitlevelcoda` includes functions to compute Isometric log ratio (ILR) for 
between and within-person levels, fit Baysian multilevel model, 
and conduct post-hoc analyses that are susbtitution models. 
See below for some useful vignettes:

* Fitting Multilevel Model with Compositional predictors:
* Fitting Multilevel Model with Compositional outcomes:
* Fitting Compositional Multilevel Substitution Model:

## References
Bürkner, P.-C. (2017). brms: An R Package for Bayesian Multilevel Models Using Stan. Journal of Statistical Software, 80(1), 1–28. https://doi.org/10.18637/jss.v080.i01

Egozcue, J. J., Pawlowsky-Glahn, V., Mateu-Figueras, G., & Barcelo-Vidal, C. (2003). Isometric logratio transformations for compositional data analysis. Mathematical geology, 35(3), 279-300.
