#' Simulate Data from Generator Specifications
#'
#' Build a single-level, grouped, or longitudinal simulation design and evaluate
#' generator specifications into one shared data table.
#'
#' @param generators Non-empty named list of generator specifications created
#'   by `gen_*()` functions.
#' @param n Total number of observations for a single-level design. For grouped
#'   designs, `n` may be supplied instead of `n_per_group`; rows are distributed
#'   as evenly as possible across groups.
#' @param n_groups Number of groups. When `NULL`, a single-level design is
#'   created.
#' @param n_per_group Group sizes. May be a scalar/vector, a function of
#'   `n_groups`, or a count-distribution list such as
#'   `list(distribution = "poisson", lambda = 4, minimum = 1)`.
#' @param group_id,obs_id Character scalars naming the group and observation
#'   index columns.
#' @param time_id Optional character scalar naming a time column.
#' @param time_values Optional time values. May be a vector shared by units or a
#'   function called per unit/group.
#' @param time_truncate Logical; when `TRUE`, vector `time_values` are truncated
#'   to each group size. When `FALSE`, every group must have the same length as
#'   `time_values`.
#' @param seed Optional random seed. When supplied, the caller's existing random
#'   seed is restored after simulation.
#'
#' @return An object of class `mlsim_data`, a list with:
#' \describe{
#'   \item{`data`}{A [data.table::data.table()] containing design columns and
#'   generated variables.}
#'   \item{`metadata`}{Simulation design metadata, seed, index metadata, and
#'   generator order.}
#'   \item{`generator_specs`}{Generator specifications with simulator closures
#'   removed.}
#'   \item{`generator_metadata`}{Per-generator metadata recorded during
#'   simulation.}
#' }
#'
#' @details
#' Generators are evaluated in list order. Each generator can depend on columns
#' produced by earlier generators through the simulation context. Generated
#' column names must be unique and must not collide after `make.names()`.
#'
#' @examples
#' sim <- simulate_data(
#'   n_groups = 3,
#'   n_per_group = 2,
#'   seed = 10,
#'   generators = list(
#'     group_x = gen_normal("group_x", level = "level2", mean = 0, sd = 1),
#'     y = gen_poisson("y", lambda = 2)
#'   )
#' )
#' sim$data
#' summary(sim)
#'
#' longitudinal <- simulate_data(
#'   n_groups = 2,
#'   n_per_group = 3,
#'   time_id = "visit",
#'   generators = list(x = gen_normal("x"))
#' )
#' longitudinal$metadata$index
#'
#' @export
simulate_data <- function(generators, n = NULL, n_groups = NULL, n_per_group = NULL,
                          group_id = "group_id", obs_id = "obs_id",
                          time_id = NULL, time_values = NULL, time_truncate = TRUE,
                          seed = NULL) {
  .mlsim_with_seed(seed, {
    generators <- .mlsim_validate_generators(generators)
    design <- .mlsim_build_design(n = n, n_groups = n_groups, n_per_group = n_per_group,
                                  group_id = group_id, obs_id = obs_id,
                                  time_id = time_id, time_values = time_values,
                                  time_truncate = time_truncate)

    data <- design$data
    design_data <- data.table::copy(design$data)
    group_data <- NULL
    if (!is.null(design$n_groups)) {
      group_data <- unique(design_data[, group_id, with = FALSE])
    }
    used_names <- names(data)
    generator_metadata <- list()

    context <- list(
      n_rows = nrow(data),
      n_groups = design$n_groups,
      group_index = design$group_index,
      group_id = group_id,
      obs_id = obs_id,
      time_id = time_id,
      time_values = if (!is.null(time_id)) data[[time_id]] else NULL,
      design_data = design_data,
      group_data = group_data,
      data = data.table::copy(data),
      index = design$index
    )

    for (generator_name in names(generators)) {
      spec <- generators[[generator_name]]
      .mlsim_check_level_possible(spec, design)

      simulated <- spec$simulate(context)
      repeated <- simulated$names %sin% used_names
      if (length(repeated) > 0L) {
        .mlsim_stop("Generator `%s` would overwrite existing columns: %s.",
                    generator_name, paste(repeated, collapse = ", "))
      }
      .mlsim_check_new_names_compatible(
        simulated$names,
        used_names,
        sprintf("columns generated by `%s`", generator_name)
      )

      if (length(simulated$names) > 0L && nrow(simulated$data) != nrow(data)) {
        .mlsim_stop("Generator `%s` returned %d rows, but the simulation design has %d rows.",
                    generator_name, nrow(simulated$data), nrow(data))
      }
      for (col in seq_along(simulated$names)) {
        data.table::set(data, j = simulated$names[[col]], value = simulated$data[[col]])
      }
      context$data <- data.table::copy(data)
      used_names <- c(used_names, simulated$names)
      generator_metadata[[generator_name]] <- simulated$metadata
    }

    structure(
      list(
        data = data,
        metadata = list(
          package = "multilevelcoda",
          seed = seed,
          n = design$n_rows,
          n_groups = design$n_groups,
          group_sizes = design$group_sizes,
          group_id = group_id,
          obs_id = obs_id,
          time_id = time_id,
          n_per_group = design$n_per_group_metadata,
          time_values = design$time_values_metadata,
          time_truncate = time_truncate,
          index = design$index,
          generator_order = names(generators)
        ),
        generator_specs = .mlsim_drop_simulators(generators),
        generator_metadata = generator_metadata
      ),
      class = "mlsim_data"
    )
  })
}

#' Internal Simulation Design Helpers
#'
#' Validate generator lists, build base simulation designs, derive time/index
#' metadata, and remove simulator closures before storing specifications on
#' `mlsim_data` objects.
#'
#' @param generators Named list of generator specifications.
#' @param n Number of observations or requested generated values.
#' @param n_groups Number of groups.
#' @param n_per_group Group-size specification.
#' @param group_id,obs_id,time_id Design column names.
#' @param time_values Optional vector or function used to create time columns.
#' @param time_truncate Logical flag controlling vector `time_values` recycling.
#' @param spec Generator specification.
#' @param design Internal design object.
#' @param group Optional group identifier passed to time-value functions.
#' @param group_sizes Integer vector of group sizes.
#' @param values Candidate time values.
#' @param data Data table containing design columns.
#' @param unit_id Unit identifier used for uniqueness checks.
#' @param grouped Logical; whether the design is grouped.
#'
#' @return Internal helper outputs used by [simulate_data()].
#'
#' @examples
#' design <- multilevelcoda:::.mlsim_build_design(
#'   n = NULL,
#'   n_groups = 2,
#'   n_per_group = 2,
#'   group_id = "group_id",
#'   obs_id = "obs_id"
#' )
#' design$data
#' multilevelcoda:::.mlsim_time_values_for_unit(NULL, 3)
#'
#' @keywords internal
#' @name multilevelcoda-internal-design
NULL

#' @rdname multilevelcoda-internal-design
.mlsim_drop_simulators <- function(generators) {
  lapply(generators, function(spec) {
    spec$simulate <- NULL
    unclass(spec)
  })
}

#' @rdname multilevelcoda-internal-design
.mlsim_validate_generators <- function(generators) {
  if (!is.list(generators) || length(generators) == 0L) {
    .mlsim_stop("`generators` must be a non-empty named list of generator specs.")
  }
  if (is.null(names(generators)) || anyNA(names(generators)) || names(generators) %any==% "") {
    .mlsim_stop("`generators` must be named.")
  }
  if (anyDuplicated(names(generators))) {
    .mlsim_stop("`generators` names must be unique.")
  }
  for (name in names(generators)) {
    if (!inherits(generators[[name]], "mlsim_generator_spec")) {
      .mlsim_stop("Generator `%s` is not an mlsim generator spec.", name)
    }
    if (!is.function(generators[[name]]$simulate)) {
      .mlsim_stop("Generator `%s` does not contain a simulator function.", name)
    }
  }
  generators
}

#' @rdname multilevelcoda-internal-design
.mlsim_build_design <- function(n, n_groups, n_per_group, group_id, obs_id,
                                time_id = NULL, time_values = NULL,
                                time_truncate = TRUE) {
  .mlsim_check_vars(group_id, 1L, "group_id")
  .mlsim_check_vars(obs_id, 1L, "obs_id")
  if (identical(group_id, obs_id)) {
    .mlsim_stop("`group_id` and `obs_id` must be different names.")
  }
  if (!is.null(time_values) && is.null(time_id)) {
    .mlsim_stop("`time_values` requires `time_id`.")
  }
  if (!is.logical(time_truncate) || length(time_truncate) != 1L || is.na(time_truncate)) {
    .mlsim_stop("`time_truncate` must be TRUE or FALSE.")
  }
  if (!is.null(time_id)) {
    .mlsim_check_vars(time_id, 1L, "time_id")
    if (time_id %anyin% c(group_id, obs_id)) {
      .mlsim_stop("`time_id` must be different from `group_id` and `obs_id`.")
    }
  }
  .mlsim_check_vars(c(group_id, obs_id, time_id), arg = "design column names")

  if (is.null(n_groups)) {
    if (is.null(n)) {
      .mlsim_stop("Single-level designs require `n` when `n_groups` is not supplied.")
    }
    n <- .mlsim_recycle_integer(n, 1L, "n")
    data <- data.table::data.table(seq_len(n))
    data.table::setnames(data, obs_id)
    time_values_metadata <- NULL
    if (!is.null(time_id)) {
      time <- .mlsim_time_values_for_unit(time_values, n, group = NULL)
      data.table::set(data, j = time_id, value = time)
      .mlsim_check_unique_time(data, unit_id = NULL, time_id = time_id)
      data.table::setorderv(data, time_id)
      data.table::set(data, j = obs_id, value = seq_len(nrow(data)))
      time_values_metadata <- .mlsim_time_values_metadata(time_values, time_truncate)
    }
    return(list(
      data = data,
      n_rows = n,
      n_groups = NULL,
      group_index = NULL,
      group_sizes = NULL,
      n_per_group_metadata = NULL,
      time_values_metadata = time_values_metadata,
      index = .mlsim_index_metadata(data, grouped = FALSE, group_id = group_id,
                                    obs_id = obs_id, time_id = time_id)
    ))
  }

  n_groups <- .mlsim_recycle_integer(n_groups, 1L, "n_groups")
  if (n_groups < 1L) {
    .mlsim_stop("`n_groups` must be at least 1.")
  }

	  if (is.null(n_per_group)) {
	    if (!is.null(n)) {
	      n <- .mlsim_recycle_integer(n, 1L, "n")
	      if (n < n_groups) {
	        .mlsim_stop("`n` must be at least `n_groups` so every group has at least one observation.")
	      }
	      base <- floor(n / n_groups)
	      remainder <- n %% n_groups
	      group_sizes <- rep(base, n_groups)
      if (remainder > 0L) {
        group_sizes[seq_len(remainder)] <- group_sizes[seq_len(remainder)] + 1L
      }
      n_per_group_metadata <- list(source = "n", n = n)
    } else {
      .mlsim_stop("Grouped designs require `n_per_group` or `n`.")
    }
  } else if (is.function(n_per_group)) {
    group_sizes <- n_per_group(n_groups)
    n_per_group_metadata <- list(source = "function")
  } else if (is.list(n_per_group)) {
    group_sizes <- .mlsim_draw_count_distribution(n_per_group, n_groups)
    n_per_group_metadata <- n_per_group
  } else {
    group_sizes <- n_per_group
    n_per_group_metadata <- list(source = "values", values = n_per_group)
  }

  group_sizes <- .mlsim_recycle_integer(group_sizes, n_groups, "n_per_group")
  if (!(group_sizes %age% 1L)) {
    .mlsim_stop("Every group must have at least one observation.")
  }

  groups <- rep(seq_len(n_groups), group_sizes)
  obs <- sequence(group_sizes)
  data <- data.table::data.table(groups, obs)
  data.table::setnames(data, c(group_id, obs_id))
  time_values_metadata <- NULL
  if (!is.null(time_id)) {
    data.table::set(data, j = time_id, value = .mlsim_group_time_values(time_values, group_sizes, time_truncate))
    .mlsim_check_unique_time(data, unit_id = group_id, time_id = time_id)
    data.table::setorderv(data, c(group_id, time_id))
    data.table::set(data, j = obs_id, value = sequence(rle(data[[group_id]])$lengths))
    groups <- data[[group_id]]
    time_values_metadata <- .mlsim_time_values_metadata(time_values, time_truncate)
  }

  list(
    data = data,
    n_rows = nrow(data),
    n_groups = n_groups,
    group_index = groups,
    group_sizes = group_sizes,
    n_per_group_metadata = n_per_group_metadata,
    time_values_metadata = time_values_metadata,
    index = .mlsim_index_metadata(data, grouped = TRUE, group_id = group_id,
                                  obs_id = obs_id, time_id = time_id)
  )
}

#' @rdname multilevelcoda-internal-design
.mlsim_check_level_possible <- function(spec, design) {
  if (spec$level %anyin% c("level2", "multilevel") && is.null(design$n_groups)) {
    .mlsim_stop("Generator with level `%s` requires `n_groups`.", spec$level)
  }
  invisible(TRUE)
}

#' @rdname multilevelcoda-internal-design
.mlsim_time_values_for_unit <- function(time_values, n, group = NULL) {
  values <- if (is.null(time_values)) {
    seq_len(n)
  } else if (is.function(time_values)) {
    .mlsim_call_time_values(time_values, n = n, group = group)
  } else {
    time_values
  }
  .mlsim_check_time_values(values, n)
}

#' @rdname multilevelcoda-internal-design
.mlsim_group_time_values <- function(time_values, group_sizes, time_truncate = FALSE) {
  if (is.null(time_values)) {
    return(sequence(group_sizes))
  }

  if (is.function(time_values)) {
    values <- lapply(seq_along(group_sizes), function(group) {
      .mlsim_time_values_for_unit(time_values, group_sizes[[group]], group = group)
    })
    return(do.call(c, values))
  }

  if (isTRUE(time_truncate)) {
    if (max(group_sizes) > length(time_values)) {
      .mlsim_stop("`time_values` must be at least as long as the largest group when `time_truncate = TRUE`.")
    }
    common_time <- .mlsim_check_time_values(time_values, length(time_values))
    return(do.call(c, lapply(group_sizes, function(size) common_time[seq_len(size)])))
  }

  if (!(group_sizes %a==% length(time_values))) {
    .mlsim_stop(
      "`time_values` must have the same length as every group size when `time_truncate = FALSE`. Use a function for group-specific time values."
    )
  }
  rep(.mlsim_check_time_values(time_values, length(time_values)), times = length(group_sizes))
}

#' @rdname multilevelcoda-internal-design
.mlsim_call_time_values <- function(time_values, n, group) {
  fn_formals <- names(formals(time_values))
  if (is.null(fn_formals)) {
    return(time_values(n))
  }

  if (c("...", "n") %anyin% fn_formals) {
    args <- list(n = n)
    if (c("...", "group") %anyin% fn_formals) {
      args$group <- group
    } else if ("group_id" %in% fn_formals) {
      args$group_id <- group
    }
    return(do.call(time_values, args))
  }

  if ("group" %in% fn_formals) {
    if (length(fn_formals) == 1L) {
      return(time_values(group = group))
    }
    return(time_values(n, group = group))
  }
  if ("group_id" %in% fn_formals) {
    if (length(fn_formals) == 1L) {
      return(time_values(group_id = group))
    }
    return(time_values(n, group_id = group))
  }
  time_values(n)
}

#' @rdname multilevelcoda-internal-design
.mlsim_check_time_values <- function(values, n) {
  if (is.data.frame(values) || is.matrix(values) || is.list(values)) {
    .mlsim_stop("`time_values` must return a vector.")
  }
  if (length(values) != n) {
    .mlsim_stop("`time_values` must have length %d.", n)
  }
  if (anyNA(values)) {
    .mlsim_stop("`time_values` must not contain missing values.")
  }
  values
}

#' @rdname multilevelcoda-internal-design
.mlsim_check_unique_time <- function(data, unit_id, time_id) {
  time_cols <- if (is.null(unit_id)) time_id else c(unit_id, time_id)
  time_index <- data.table::as.data.table(lapply(time_cols, function(col) data[[col]]))
  data.table::setnames(time_index, time_cols)
  if (any(duplicated(time_index))) {
    if (is.null(unit_id)) {
      .mlsim_stop("`time_values` must be unique.")
    }
    .mlsim_stop("`time_values` must be unique within each `%s`.", unit_id)
  }
  invisible(TRUE)
}

#' @rdname multilevelcoda-internal-design
.mlsim_time_values_metadata <- function(time_values, time_truncate = FALSE) {
  if (is.null(time_values)) {
    list(source = "sequence")
  } else if (is.function(time_values)) {
    list(source = "function")
  } else {
    list(source = if (isTRUE(time_truncate)) "truncated_values" else "values", values = time_values)
  }
}

#' @rdname multilevelcoda-internal-design
.mlsim_index_metadata <- function(data, grouped, group_id, obs_id, time_id) {
  longitudinal <- !is.null(time_id)
  list(
    longitudinal = longitudinal,
    unit_id = if (grouped) group_id else NULL,
    obs_id = obs_id,
    time_id = time_id,
    order = if (longitudinal) {
      if (grouped) c(group_id, time_id) else time_id
    } else {
      if (grouped) c(group_id, obs_id) else obs_id
    },
    time_type = if (longitudinal) paste(class(data[[time_id]]), collapse = "/") else NULL,
    time_unique_within_unit = if (longitudinal) TRUE else NULL
  )
}
