# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release', rtools: ''}
          - {os: windows-latest, r: 'release', rtools: '44'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release', rtools: ''}
          - {os: ubuntu-latest,  r: 'release', rtools: ''}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      
      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev || true
          sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev || true
          
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.rtools }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: NA
          extra-packages: |
            any::rcmdcheck
            BH
            RcppEigen
            stan-dev/cmdstanr
            testthat
            knitr
            rmarkdown
            doFuture
            lme4
            covr
          needs: check
            
      - name: Build Cmdstan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = parallel::detectCores())
        shell: Rscript {0}
        
      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual", "--no-build-vignettes")'
          args: 'c("--no-manual", "--as-cran", "--ignore-vignettes")'